---
cisco_ios:
  platform: ios
  username: admin
  password: cisco123
  #data:
    #img: c880data-universalk9-mz.155-3.M8.bin
    #backup_img: c880data-universalk9-mz.154-2.T1.bin
C899G:
  data:
    img: 899g.txt
    backup_img:
C2900:
  data:
    img: isr2900.txt
    backup_img: c2900-universalk9-mz.SPA.157-3.M4a.bin
iosv:
  data:
    #img:  Collector-2.8.1.4-B-04.ova
    #img: vios-adventerprisek9-m.vmdk.SPA.155-3.M
    img: iosv-fakeimg.txt
  connection_options:
    napalm:
      extras:
        optional_args:
            secret: cisco123
    netmiko:
      extras:
        secret: cisco123
