---
HRN6W3-GMALAB-GW1:
  hostname: 10.83.46.1
  groups:
    - cisco_ios
    - C2900
TermServer-4221:
  hostname: 10.83.46.149
  groups:
    - cisco_ios
C9300-DNA-A-24:
  hostname: 10.83.8.142
  groups:
    - cisco_ios
    - C899G
Router1:
  hostname: 10.83.8.165
  groups:
    - cisco_ios
    #- iosv
Router2:
  hostname: 10.83.8.172
  groups:
    - cisco_ios
    #- iosv
Router3:
  hostname: 10.83.8.173
  groups:
    - cisco_ios
    #- iosv
C899G-LTE:
  hostname: 192.168.1.47
  groups:
    - cisco_ios
    - iosv
